[package]
name = "DynamicLabelPropagation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
smartcore = "0.2.0"
ndarray = "0.15.4"
